all:
	cat presentation/besoins.md presentation/description_solution.md presentation/description_technique.md marketing/marche.md marketing/plan_marketing.md marketing/finance.md previsionnel/management_projet.md previsionnel/licence.md previsionnel/evolutions.md annexes/business_model_canvas.md annexes/ressources.md annexes/lots.md annexes/liste_fonctionnalites.md > oseo.md
	cd .. && ./md2pdf oseo/oseo.md
	rm oseo.md

